# Generated by Django 4.0.1 on 2022-03-28 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('discriptiom', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='product_img')),
            ],
        ),
    ]
