# Generated by Django 4.0.1 on 2022-04-21 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_addnews'),
    ]

    operations = [
        migrations.CreateModel(
            name='addnews2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title2', models.CharField(max_length=250)),
            ],
        ),
    ]
